name: nightly

on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  push:
  pull_request:
  workflow_dispatch:

env:
   SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}
   ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
   ARM_TOKEN: ${{ secrets.ARM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install json tool
        run: sudo apt-get install jq
     
      - name: Test saving the environment variables
        env:
          ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
          ARM_PASSWORD: ${{ secrets.ARM_TOKEN }}
          SECRETS_VARS: ${{ toJson(secrets) }}
        run: |
          jq -r 'keys_unsorted[]' $SECRETS_VARS
