name: nightly

on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  push:
  pull_request:
  workflow_dispatch:

env:
   SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}
   ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
   ARM_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup miniconda environment
        uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          activate-environment: test-actions
          auto-update-conda: false
          python-version: 3.9
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true
     
      - name: Set TRMM RSL path
        run: |
          mamba install -c conda-forge trmm_rsl
          export RSL_PATH=${{ env.CONDA_PKGS_DIR }}/trmm_rsl-1.49-3

      - name: Install Py-ART
        run: |
          mamba install pip
          python -m pip install git+https://github.com/ARM-DOE/pyart --force-reinstall
          
      - name: Check RSL Path
        env:
          RSL_PATH: ${{ env.CONDA_PKGS_DIR }}/trmm_rsl-1.49-3
        run: |
          echo $RSL_PATH
          conda list
