name: nightly

on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  push:
  pull_request:
  workflow_dispatch:

env:
   SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}
   ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
   ARM_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Test saving the environment variables
        env:
          ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
          ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
        run: |
          printenv
